pipeline {
    agent any

    environment {
        cluster = "vproprod"
        service = "vproappprodsvc"
    }
    stages {
        stage('Deploy to prod ecs') {
            steps {
                withAWS(credentials: 'awscreds', region: 'eu-west-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
}